### ISSUE TITLE
Duplicate updater.sh

### ISSUE THREAD

**Issue by gonsoos** [Lab-Brat/gentoo_update#7]
Merging this project via any of the provided methods (`emerge` or `pip`) installs a duplicate `updater.sh` into the PATH. As far as I can tell, `gentoo-update` should be the only public facing script.

Please fix the build system if this is indeed a bug.

**Comment by Lab-Brat** [comment]
@antecrescent Thank you for noticing this (and improving the ebuild 🫶)
It was designed like that as a temporary workaround, I will fix it in the next version.

**Comment by gonsoos** [comment]
Great, thanks!

**Comment by Lab-Brat** [comment]
The issue is fixed in version 0.1.4 

I will not upload ebuild to GURU yet, at least until I figure out what causes errors in their CI/CD system.
But it's available to install with pip 😊

**Comment by Lab-Brat** [comment]
version [0.1.4](https://github.com/gentoo/guru/blob/master/app-admin/gentoo_update/gentoo_update-0.1.4.ebuild) is in GURU repo now and is available for download
